import java.awt.*;
import javax.swing.*;
import javax.swing.event.ChangeListener;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author lilob
 */
public class MainFrame extends javax.swing.JFrame {
    
    

    //försökte använda this istället för static. men jag är för bajs på oop.
    public static Color Col = Color.BLACK;
    public static int SizeRelay = 10;
    public static int Shaper = 0;
    public static boolean Deletethose = false;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        Size.addChangeListener(e -> {
        SizeRelay = Size.getValue();
            System.out.println(SizeRelay);
            SizeLabel2.setText(""+SizeRelay);
    });
    Colpicr.getSelectionModel().addChangeListener(e -> {
        Color c = Colpicr.getColor();
            System.out.println(c);
            Col = c;
});   
    ShapeSelect.addActionListener(e -> {
        int Shaplin = ShapeSelect.getSelectedIndex();
            System.out.println(Shaplin);
            Shaper = Shaplin;
});  
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mP1 = new MP();
        ShapeSelect = new javax.swing.JComboBox<>();
        Size = new javax.swing.JSlider();
        Colpicr = new javax.swing.JColorChooser();
        jLabel1 = new javax.swing.JLabel();
        ColPicToggler = new javax.swing.JButton();
        SizeLabel2 = new javax.swing.JLabel();
        EraserButton = new javax.swing.JButton();
        UndoButton = new javax.swing.JButton();
        RedoButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1600, 900));

        mP1.setPreferredSize(new java.awt.Dimension(960, 540));

        ShapeSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sphere", "Square" }));

        Size.setMaximum(250);
        Size.setMinimum(1);
        Size.setValue(10);

        jLabel1.setText("Size");

        ColPicToggler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ColorIcon.png"))); // NOI18N
        ColPicToggler.setText("Color");
        ColPicToggler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColPicTogglerActionPerformed(evt);
            }
        });

        SizeLabel2.setText("10");

        EraserButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EraserIcon.png"))); // NOI18N
        EraserButton.setText("Eraser");
        EraserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EraserButtonActionPerformed(evt);
            }
        });

        UndoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Undo.png"))); // NOI18N
        UndoButton.setText("Undo");
        UndoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UndoButtonActionPerformed(evt);
            }
        });

        RedoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Redo.png"))); // NOI18N
        RedoButton.setText("Redo");
        RedoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RedoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mP1Layout = new javax.swing.GroupLayout(mP1);
        mP1.setLayout(mP1Layout);
        mP1Layout.setHorizontalGroup(
            mP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mP1Layout.createSequentialGroup()
                .addGroup(mP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(mP1Layout.createSequentialGroup()
                        .addComponent(ShapeSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ColPicToggler)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EraserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UndoButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RedoButton)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Size, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SizeLabel2)
                        .addGap(6, 6, 6))
                    .addComponent(Colpicr, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 303, Short.MAX_VALUE))
        );
        mP1Layout.setVerticalGroup(
            mP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mP1Layout.createSequentialGroup()
                .addGroup(mP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ShapeSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ColPicToggler)
                        .addComponent(EraserButton)
                        .addComponent(UndoButton)
                        .addComponent(RedoButton))
                    .addComponent(Size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SizeLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Colpicr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 159, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mP1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mP1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ColPicTogglerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColPicTogglerActionPerformed
        if (Colpicr.isVisible() == false)
        Colpicr.setVisible(true);
        else
        Colpicr.setVisible(false);
    }//GEN-LAST:event_ColPicTogglerActionPerformed

    private void EraserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EraserButtonActionPerformed
        if (Deletethose == false) {
            EraserButton.setText("Draw");
            Deletethose = true;
        }
            else {
            Deletethose = false;
            EraserButton.setText("Eraser");
                    }
    }//GEN-LAST:event_EraserButtonActionPerformed

    private void UndoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UndoButtonActionPerformed
        mP1.SuperUndo();
    }//GEN-LAST:event_UndoButtonActionPerformed

    private void RedoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RedoButtonActionPerformed
        mP1.SuperRedo();
    }//GEN-LAST:event_RedoButtonActionPerformed


    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ColPicToggler;
    private javax.swing.JColorChooser Colpicr;
    private javax.swing.JButton EraserButton;
    private javax.swing.JButton RedoButton;
    private javax.swing.JComboBox<String> ShapeSelect;
    private javax.swing.JSlider Size;
    private javax.swing.JLabel SizeLabel2;
    private javax.swing.JButton UndoButton;
    private javax.swing.JLabel jLabel1;
    private MP mP1;
    // End of variables declaration//GEN-END:variables
}

