import java.awt.*;
import javax.swing.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.Stack;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author lilob
 */
public class MP extends javax.swing.JPanel {

    private int mx = 100;
    private int my = 100;
    private List<AllKnowingMP> Knowledge = new ArrayList<>();
    private Stack<AllKnowingMP> SuperUndoLegend = new Stack<>();
    private Stack<AllKnowingMP> SuperRedoLegend = new Stack<>();


//bombaclat pencil
public MP() {
    initComponents();
    addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent m) {
            mx = m.getX();
            my = m.getY();
            if (MainFrame.Deletethose != true){
            AllKnowingMP unc = new AllKnowingMP(mx, my, MainFrame.Shaper, MainFrame.Col, MainFrame.SizeRelay);
            SuperUndoLegend.push(unc);
            SuperRedoLegend.clear();
            repaint();}
            else {
            Strike(mx, my);
                }
            }
        });
}
//bombaclat object
    class AllKnowingMP{
        int x, y, size, type;
        Color color;
        boolean erased;
        
        AllKnowingMP(int x, int y, int type, Color color, int size){
        this.x = x;
        this.y = y;
        this.type = type;
        this.color = color;
        this.size = size;
        this.erased = false;
        }
    }
 //bombaclat painter
 @Override 
 protected void paintComponent(Graphics g) {
 super.paintComponent(g); //clears bg
 Graphics2D g2 = (Graphics2D) g;
 g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
 for(AllKnowingMP k : SuperUndoLegend) {
     if(k.erased) continue;
 g2.setColor(k.color);
 if (k.type == 0) {
    g2.fillOval(k.x - (k.size/2), k.y - (k.size/2), k.size, k.size);
 }
 else if (k.type == 1){
    g2.fillRect(k.x - (k.size/2), k.y - (k.size/2), k.size, k.size);}
 }}
//bombaclat eraser
private void Strike(int mx, int my) {
    for(int oil = SuperUndoLegend.size() -  1; oil >= 0; oil--){
    AllKnowingMP constitution = SuperUndoLegend.get(oil);
    int bugfix = constitution.size/2;
    if(constitution.erased) {continue;}
    if(mx >= constitution.x - bugfix && mx <= constitution.x + bugfix && my >= constitution.y - bugfix && my <= constitution.y + bugfix){
        //SuperUndoLegend.remove(oil);
        constitution.erased = true;
        SuperRedoLegend.clear();
        repaint();
        return;
        }
    }
}

public void SuperUndo() {
    if (!SuperUndoLegend.isEmpty()){
        //SuperRedoLegend.push(SuperUndoLegend.pop());
        AllKnowingMP action = SuperUndoLegend.pop();
        SuperRedoLegend.push(action);
        if(action.erased) {action.erased = false;}
        else {action.erased = true;}
        System.out.println("Undid last change");
        repaint();
       
    }
}

public void SuperRedo() {
    if (!SuperRedoLegend.isEmpty()){
        //SuperUndoLegend.push(SuperRedoLegend.pop());
        AllKnowingMP action = SuperRedoLegend.pop();
        if(action.erased) {action.erased = true;}
        else {action.erased = false;}
        System.out.println("Redid last change (regret is for the weak)");
        repaint();
    }
}

    public void Undo() {
        SuperUndo();
}

    public void Redo() {
        SuperRedo();
}


    //bombaclat netbeans
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor. -- Sincerely Netbeans xoxo hugs and kisses forever.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
